### ISSUE TITLE
District value not getting populated in database

### ISSUE THREAD

**Issue by GauravGusain98** [DostEducation/RP_IVR_analytics#315] opened 2022-12-05 09:33 UTC
**Describe the bug**
For new users who are selecting a district via prompts, the district data is not getting updated in the registration table. Though the mapping exists in the ivr_prompt_mapping table.

**Diagnosis Query**
```sql
WITH last_week_users as (
    SELECT 
        RIGHT(user_phone, 10) as phone, 
        user_id, 
        program_id as db_program_id, 
        district as db_district
    FROM registration
    WHERE created_on::date BETWEEN '2022-11-14' and now()::date
    AND system_phone LIKE '%703'
    GROUP BY 1, 2, 3, 4
), time_selection_prompt_option as (
    SELECT RIGHT(user_phone, 10) as phone, response as selected_time 
    FROM ivr_prompt_response
    WHERE RIGHT(user_phone, 10) in (SELECT phone from last_week_users)
    AND prompt_name = 'INTRO_1-SIGNUP_1-SELECTION_TIME-OPTIN'
), district_selected as (
    SELECT RIGHT(user_phone, 10) as phone, response as selected_district 
    FROM ivr_prompt_response
    WHERE RIGHT(user_phone, 10) in (SELECT phone from last_week_users)
    AND prompt_name = 'partner_code'
), program_selected as (
    SELECT RIGHT(user_phone, 10) as phone, response as selected_program 
    FROM ivr_prompt_response
    WHERE RIGHT(user_phone, 10) in (SELECT phone from last_week_users)
    AND prompt_name = 'INTRO_1-SIGNUP_1-SELECTION_PROGRAM-OPTIN'
)
SELECT 
    last_week_users.*, 
    selected_time, 
    selected_district,
    selected_program
FROM last_week_users
LEFT JOIN time_selection_prompt_option
ON last_week_users.phone = time_selection_prompt_option.phone
LEFT JOIN district_selected
ON last_week_users.phone = district_selected.phone
LEFT JOIN program_selected
ON last_week_users.phone = program_selected.phone;
```
**To Reproduce**
1. Run the query and see the `db_district` column OR you can see this [sheet](https://docs.google.com/spreadsheets/d/1_W40WGqIT7fiV_gd0rBRIzZtBxN_tHQ7cCDEySFQw_Q/edit#gid=0)

**Expected behavior**
The district data should be populated in the table as per the mapping available.

**Acceptance Criteria**
- [x] Share the Diagnosis Report
- [x] Fix the issue 
- [ ] Correct old data

**Documentation**
NA

**Comment by Satendra-SR** [comment] 2022-12-07 05:05
@prtkdost sharing an update from our discussion this morning.
As the reason is still unknown, which I’m trying to figure out, but as it is happening randomly, I’m expecting a bit more time to find the exact root cause, and fix it.
This morning, we discussed, that we can just divide it into two phases
Phase 1: Backfill the data for existing users till 5th Dec, who already selected the prompt, but the registration table is not updated.
Phase 2: Find the root cause, fix and deploy it on production and then backfill the remaining user's data from 6th Dec onwards.
Let me know your thoughts/suggestions.

**Comment by Satendra-SR** [comment] 2022-12-11 07:26
**Diagnosis Report:** 
- We have added a new 'District Prompt' for UP District **UTKARSH** whose prompt name was wrong in **IVR_prompt** table. 
- When the response of user was coming for that prompt name. There was no mapped possible response in the **IVR_prompt_mapping** table. 
- Therefore, the system is fetching the user response in **IVR_prompt_response** table. But not able to update it in the mapped table.

**Solution:** 
- We have to delete that prompt of **UTKARSH** district and need to add a new correct prompt in **IVR_prompt** table.

**Comment by Satendra-SR** [comment] 2022-12-14 07:36
**Test cases:**
- Replicating the bug while the mapping for **UTKARSH** is not available. No districts are updating.
- After merging fixes other districts are updating than **UTKARSH** till we added the mapping for it.
- Updating **registration** table's **district** column for all districts.

**Comment by Satendra-SR** [comment] 2022-12-16 05:26
The changes are released on prod and the backfilling is completed, here is the list -  https://docs.google.com/spreadsheets/d/1IAwHtynSTsARELMoSPXozOl6ZDGpYajscJ_fUyLXHIE/edit#gid=2064845584

**Comment by Satendra-SR** [comment] 2022-12-21 04:14
Closing as this is complete

**Closed by Satendra-SR** 2022-12-21 04:14 UTC
